#!/usr/bin/env python3
"""Render a self-contained HTML preview of the Tandayapa report.

R/pandoc are not available on the build host, so we cannot knit the .Rmd here.
This builds a portable single-file HTML from the report markdown: prose + results
tables + the figures embedded as base64, with the full R Markdown code appended as
an appendix. The .Rmd is the live (knit-to-HTML) source; this is a viewable preview.

Run: .venv-perch/bin/python reports/render_report_html.py
"""
import base64
import re
from pathlib import Path

import markdown  # available in .venv-perch

HERE = Path(__file__).resolve().parent
MD = HERE / "tandayapa_spacing_biodiversity_report.md"
RMD = HERE / "tandayapa_spacing_biodiversity_report.Rmd"
OUT = HERE / "tandayapa_spacing_biodiversity_report.html"

CSS = """
body{max-width:900px;margin:2rem auto;padding:0 1.2rem;font:16px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#22302a;background:#fbfcfa}
h1{font-size:1.9rem;line-height:1.25;color:#1E4220;border-bottom:3px solid #97BC62;padding-bottom:.4rem}
h2{font-size:1.4rem;color:#2C5F2D;margin-top:2rem;border-bottom:1px solid #e3e9df;padding-bottom:.25rem}
h3{font-size:1.15rem;color:#3a5a3b}
blockquote{border-left:4px solid #97BC62;margin:1rem 0;padding:.5rem 1rem;background:#f1f5ee;color:#3a4a3f;border-radius:0 6px 6px 0}
table{border-collapse:collapse;width:100%;margin:1rem 0;font-size:.95rem}
th,td{border:1px solid #dce4d6;padding:.45rem .7rem;text-align:left}
th{background:#eaf0e4;color:#2C5F2D}
tr:nth-child(even){background:#f6f9f3}
img{max-width:100%;height:auto;display:block;margin:1rem auto;border:1px solid #e3e9df;border-radius:6px}
code{background:#eef2ea;padding:.1rem .3rem;border-radius:3px;font-size:.9em}
pre{background:#1d251e;color:#e8efe6;padding:1rem;border-radius:8px;overflow:auto;font-size:.86rem;line-height:1.45}
pre code{background:none;color:inherit;padding:0}
.note{background:#fdf6e3;border:1px solid #e6d9a8;border-radius:6px;padding:.6rem .9rem;font-size:.9rem;color:#6b5b1f;margin:1rem 0}
em{color:#3a4a3f}
"""


def embed_images(html: str) -> str:
    def repl(m):
        src = m.group(1)
        p = (HERE / src).resolve()
        if not p.exists():
            return m.group(0)
        data = base64.b64encode(p.read_bytes()).decode()
        return f'src="data:image/png;base64,{data}"'
    return re.sub(r'src="([^"]+\.png)"', repl, html)


def main():
    md_text = MD.read_text()
    body = markdown.markdown(md_text, extensions=["tables", "fenced_code", "toc", "sane_lists"])
    body = embed_images(body)

    rmd_code = RMD.read_text()
    appendix = (
        '<h2 id="appendix">Appendix — R Markdown source (analysis code)</h2>'
        '<div class="note">This HTML is a self-contained <b>preview</b> rendered without R '
        '(R/pandoc are not installed on the build host). To produce the live document with the '
        'code executed inline, knit the companion <code>.Rmd</code> on a machine with R '
        '(<code>rmarkdown::render("tandayapa_spacing_biodiversity_report.Rmd")</code>). '
        'The figures and numbers above were generated by the identical analysis '
        '(<code>analysis/biodiversity_distance_decay.py</code> / <code>.R</code>).</div>'
        "<pre><code>" + rmd_code.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") + "</code></pre>"
    )

    html = (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>Tandayapa · recorder-spacing biodiversity report</title>"
        f"<style>{CSS}</style></head><body>{body}{appendix}</body></html>"
    )
    OUT.write_text(html)
    print(f"wrote {OUT}  ({len(html)//1024} KB, figures embedded)")


if __name__ == "__main__":
    main()
